#ifndef DEFINES_H
#define DEFINES_H

#define LENGTH_LOGIN			20
#define LENGTH_PASSWORD			20
#define LENGTH_ROOM_NAME		100
#define LENGTH_NICKNAME			40

#define PROTOCOL_AUTHORIZATION_FAILED		0
class CJsonDoc;

#endif // DEFINES_H
